import type { MigrationPlan, WorkItem, ExportFormat } from "../types";
import { PHASE_NAME } from "../domain";

/**
 * Export serializers (brief 16.4). Pure string producers. The resolver stores
 * the result in the Object Store and returns only a presigned URL, so a large
 * export never crosses the 5 MB resolver response cap (DECISIONS.md).
 */

export function toJSON(plan: MigrationPlan, items: WorkItem[]): string {
  return JSON.stringify({ plan, workItems: items }, null, 2);
}

export function toMarkdown(plan: MigrationPlan, items: WorkItem[]): string {
  const lines: string[] = [
    `# BoxLang migration plan: ${plan.projectName}`,
    "",
    `Scanned ${plan.scannedAt.slice(0, 10)}.`,
    "",
    "## Executive summary",
    "",
    plan.executiveSummary,
    "",
    "## Phasing",
    "",
    "| Phase | Work items | Hours | Sprints |",
    "| --- | --- | --- | --- |",
    ...plan.phases.map(
      (p) =>
        `| Phase ${p.phase}: ${p.name} | ${p.workItemCount} | ${p.totalHours} | ${p.sprintRecommendation.sprints} |`,
    ),
    "",
  ];
  for (const phase of plan.phases) {
    lines.push(`## Phase ${phase.phase}: ${phase.name}`, "");
    const phaseItems = items.filter((w) => w.phase === phase.phase);
    if (phaseItems.length === 0) {
      lines.push("No work items in this phase.", "");
      continue;
    }
    for (const wi of phaseItems) {
      lines.push(
        `### ${wi.id} ${wi.title}`,
        "",
        `Category ${wi.category}, severity ${wi.severity}, ${wi.effort.storyPoints} points, ${wi.occurrences} occurrence(s).`,
        "",
        `Rationale: ${wi.rationale}`,
        "",
        `Recommendation: ${wi.recommendation}`,
        "",
      );
    }
  }
  return lines.join("\n");
}

function csvCell(s: string): string {
  return `"${s.replace(/"/g, '""').replace(/\r?\n/g, " ")}"`;
}

/** Jira CSV import compatible (brief 16.4). */
export function toCSV(_plan: MigrationPlan, items: WorkItem[]): string {
  const header = [
    "Summary",
    "Issue Type",
    "Priority",
    "Labels",
    "Category",
    "Severity",
    "Story Points",
    "File",
    "Rationale",
    "Recommendation",
  ];
  const rows = items.map((wi) =>
    [
      wi.title,
      wi.jiraIssueType,
      wi.priority,
      [...wi.tags, "cartographer", "boxlang-migration", wi.category].join(" "),
      wi.category,
      wi.severity,
      String(wi.effort.storyPoints),
      `${wi.location.file}:${wi.location.startLine}`,
      wi.rationale,
      wi.recommendation,
    ]
      .map(csvCell)
      .join(","),
  );
  return [header.map(csvCell).join(","), ...rows].join("\n");
}

function shq(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}

/** Idempotent `gh issue create` wrapper (brief 16.4). */
export function toGhScript(plan: MigrationPlan, items: WorkItem[]): string {
  const lines: string[] = [
    "#!/usr/bin/env bash",
    "# Generated by Cartographer for Atlassian. Idempotent: an issue with the",
    "# same title is not recreated. Requires the GitHub CLI (gh).",
    "set -euo pipefail",
    "",
    `echo ${shq(`BoxLang migration: ${plan.projectName} (${items.length} work items)`)}`,
    "",
    "create_issue() {",
    "  local title=$1 body=$2 labels=$3",
    '  if gh issue list --state all --search "$title in:title" --json title \\',
    "       --jq '.[].title' | grep -Fxq \"$title\"; then",
    '    echo "skip (exists): $title"',
    "    return 0",
    "  fi",
    '  gh issue create --title "$title" --body "$body" --label "$labels"',
    "}",
    "",
  ];
  for (const wi of items) {
    const labels = `cartographer,boxlang-migration,${wi.category}`;
    const body = `Phase ${wi.phase} ${PHASE_NAME[wi.phase]}. ${wi.rationale} Recommendation: ${wi.recommendation} Location: ${wi.location.file}:${wi.location.startLine}.`;
    lines.push(
      `create_issue ${shq(`${wi.id} ${wi.title}`)} ${shq(body)} ${shq(labels)}`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

export function serialize(
  format: ExportFormat,
  plan: MigrationPlan,
  items: WorkItem[],
): { content: string; contentType: string; ext: string } {
  switch (format) {
    case "json":
      return {
        content: toJSON(plan, items),
        contentType: "application/json",
        ext: "json",
      };
    case "markdown":
      return {
        content: toMarkdown(plan, items),
        contentType: "text/markdown",
        ext: "md",
      };
    case "csv":
      return {
        content: toCSV(plan, items),
        contentType: "text/csv",
        ext: "csv",
      };
    case "gh-script":
      return {
        content: toGhScript(plan, items),
        contentType: "text/x-shellscript",
        ext: "sh",
      };
  }
}
